### PR TITLE
CRAN ready

### PR DESCRIPTION
**Pull request by schloerke**
I submitted this to CRAN on your behalf.  They should be sending you an email to confirm.  The only code change was for lintr.
- Barret

### CODE REVIEW

**Comment by schloerke** [comment]
Solves #1

**Comment by hafen** [comment]
Thanks!!  Have you checked the CRAN-submitted version to make sure the lazy loading works (i.e. did you generate a page and manually inspect that widgets are being lazily loaded)?  That's something that is hard to test, but it would be good to double check that we didn't break anything in the process of the updates we have made in the last week.

**Comment by schloerke** [comment]
I added a vig that displays the lazy example.  Since it's a force directed graph, it wiggles on load.  The first graph does not wiggle as it takes a while for you to find it.  The second graph wiggles as it's lazy loaded.

Resubmit to cran?

**Comment by schloerke** [comment]
I'm running build_win now

**Comment by schloerke** [comment]
Submitted again

**Pull request merged**
